%% Search for a specified operating point for the model - simplified_sim_for_linearize.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 24.2 and Simulink Control Design (TM) 24.2.
%
% Generated on: 21-Mar-2025 19:51:32


function [operpoint, opreport] = find_operpoint(opts)
arguments 
    opts.model = "simplified_sim_for_linearize";
    opts.z = -0.3;
    opts.usted = 7;
    opts.u1min = -0.2;
    opts.u1max = 0.2;
    opts.u2min = -0.2;
    opts.u2max = 0.2;
    opts.u3min = -0.2;
    opts.u3max = 0.2;
    opts.u4 = 2500;
    opts.u4min = 0;
    opts.u4max = Inf;
end
%% Specify the model name
%model = 'simplified_sim_for_linearize';

%% Create the operating point specification object.
opspec = operspec(opts.model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - simplified_sim_for_linearize/Hydrofoil Craft/int_EUL-ANG
% - Default model initial conditions are used to initialize optimization.
opspec.States(1).Known = [true;true;true];

% State (2) - simplified_sim_for_linearize/Hydrofoil Craft/int_POS
% - Default model initial conditions are used to initialize optimization.
opspec.States(2).SteadyState = [false;false;true];

% State (3) - simplified_sim_for_linearize/Hydrofoil Craft/int_RATES
% - Default model initial conditions are used to initialize optimization.
opspec.States(3).x = [opts.usted;0;0;0;0;0];
opspec.States(3).Known = [true;false;false;false;false;true];
opspec.States(3).SteadyState = [true;false;true;true;true;false];


%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - simplified_sim_for_linearize/AoA_1
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(1).Min = opts.u1min;
opspec.Inputs(1).Max = opts.u1max;

% Input (2) - simplified_sim_for_linearize/AoA_2
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(2).Min = opts.u2min;
opspec.Inputs(2).Max = opts.u2max;

% Input (3) - simplified_sim_for_linearize/AoA_3
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(3).Min = opts.u3min;
opspec.Inputs(3).Max = opts.u3max;



% Input (4) - simplified_sim_for_linearize/rpm
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(4).Min = opts.u4min;
opspec.Inputs(4).Max = opts.u4max;
opspec.Inputs(4).u = opts.u4; % set rpm

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - simplified_sim_for_linearize/z
opspec.Outputs(1).y = opts.z;
opspec.Outputs(1).Known = true;

% Output (2) - simplified_sim_for_linearize/phi
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(2).Known = true;

% Output (3) - simplified_sim_for_linearize/theta
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(3).Known = true;

% Output (4) - simplified_sim_for_linearize/w
% - Default model initial conditions are used to initialize optimization.

% Output (5) - simplified_sim_for_linearize/p
% - Default model initial conditions are used to initialize optimization.

% Output (6) - simplified_sim_for_linearize/q
% - Default model initial conditions are used to initialize optimization.


%% Create the options
opt = findopOptions('DisplayReport','iter');

%% Perform the operating point search.
[operpoint,opreport] = findop(opts.model,opspec,opt);
end