%% Exact linearization of the Simulink model simplified_sim_for_linearize
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 24.2 and Simulink Control Design (TM) 24.2.
%
% Generated on: 21-Mar-2025 19:55:04

function [linearsys] = find_linear_model(opts)
arguments
    opts.model = 'simplified_sim_for_linearize';
    opts.operpoint = [];
end


%% Specify the analysis I/Os
% Get the analysis I/Os from the model
io = getlinio(opts.model);

%% Specify the operating point
% Create the operating point variable op_trim1 using model initial condition as a starting point
op = opts.operpoint;
% Set the states in the model with different values than model initial condition
% State (1) - simplified_sim_for_linearize/Hydrofoil Craft/int_EUL-ANG
op.States(1).x = [0;0;0];
% State (2) - simplified_sim_for_linearize/Hydrofoil Craft/int_POS
op.States(2).x = [0;0;-0.3];
% State (3) - simplified_sim_for_linearize/Hydrofoil Craft/int_RATES
%op.States(3).x = [ops.usted;0;0;0;0;0];


%% Specify the custom state ordering
stateorder = {'simplified_sim_for_linearize/Hydrofoil Craft/int_POS',...
    'simplified_sim_for_linearize/Hydrofoil Craft/int_EUL-ANG',...
    'simplified_sim_for_linearize/Hydrofoil Craft/int_RATES'};
%% Linearize the model
linearsys = linearize(opts.model,io,op,'StateOrder',stateorder);

%% Plot the resulting linearization
%step(sys)

